name: tiny-java
version: 0.0.0
synopsis: A compiler for a subset of Java
description: This compiler was programmed as a part of the \"Compilerbau\" seminar by Prof. Martin Plümicke.
license: MIT
copyright: No one
author: Morty Smith <morty@smith.net>
maintainer: Rick Sanchez <rick@sanchez.net>

ghc-options: -Wall -fno-warn-name-shadowing

default-extensions: DuplicateRecordFields

dependencies:
 - base == 4.*
 - megaparsec == 6.*
 - bytestring == 0.10.8.*
 - text == 1.2.*

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - tiny-java
      - hspec == 2.*
